# Default configuration for GravelEssentialsX

# Debug-Mode (true/false)
debug: false

# TPA System Configuration
tpa:

  request-timeout-seconds: 60

  cooldown-seconds: 60

  warmup-seconds: 3

# MySQL Config
mysql:
  enabled: true
  host: "localhost"
  port: 3306
  database: "minecraft"
  username: "minecraft"
  password: "minecraft"
  connection-pool-size: 5
  ssl: false
  auto-reconnect: true
  timeout-seconds: 30


